version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_PUBLIC_URL: postgresql://postgres:kpljCtwbeZSnbclsqeLUpBdcfbXeqnjt@junction.proxy.rlwy.net:45589/railway

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kpljCtwbeZSnbclsqeLUpBdcfbXeqnjt
      # Disable host authentication for local setup only
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    external: false

# # services:
# #   db:
# #     image: postgres:14-alpine
# #     ports:
# #       - '5432:5432'
# #     restart: 'no'
# #     environment:
# #       - POSTGRES_DB=siap
# #       - POSTGRES_USER=postgres
# #       - POSTGRES_PASSWORD=secret99
# #     volumes:
# #       - db:/var/lib/postgresql/data
# # volumes:
# #   db:
# #     driver: local

# version: '3.8'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: railway
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: kpljCtwbeZSnbclsqeLUpBdcfbXeqnjt
#       POSTGRES_HOST_AUTH_METHOD: trust
#     ports:
#       - "5432:5432"
#     networks:
#       - default

# networks:
#   default:
#     external: false
